/**
 * Character roster — 4×4 grid (16 frames) per character
 * Frame layout:
 *   Row 0: idle1(0), idle2(1), walk1(2), walk2(3)
 *   Row 1: punch_start(4), punch_active(5), kick_start(6), kick_active(7)
 *   Row 2: block(8), hurt(9), fireball_start(10), fireball_release(11)
 *   Row 3: jump_rise(12), jump_fall(13), knockdown(14), victory(15)
 */
export const ROSTER = [
  {
    id: 'blaze',
    name: 'BLAZE',
    subtitle: 'Street King',
    sprite: '/sprites/fighter1.png',
    cols: 4,
    rows: 4,
    color: 0x3388ff,
    colorCSS: '#3388ff',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 4, loop: true },
      walk:     { frames: [2, 3], rate: 8, loop: true },
      punch:    { frames: [4, 5], rate: 14, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 14, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 12, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 8, power: 7, defense: 5 },
    specials: [
      { name: 'Soul Blast', cost: 25, type: 'fireball', damage: 20 },
      { name: 'Rising Flame', cost: 40, type: 'uppercut', damage: 25 },
      { name: 'Quake Slam', cost: 50, type: 'groundSlam', damage: 30 },
    ],
  },
  {
    id: 'venom',
    name: 'VENOM',
    subtitle: 'Street Legend',
    sprite: '/sprites/fighter2.png',
    cols: 4,
    rows: 4,
    color: 0xff6622,
    colorCSS: '#ff6622',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 3, loop: true },
      walk:     { frames: [2, 3], rate: 7, loop: true },
      punch:    { frames: [4, 5], rate: 12, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 12, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 10, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 6, power: 9, defense: 7 },
    specials: [
      { name: 'Fire Fist', cost: 25, type: 'fireball', damage: 22 },
      { name: 'Dragon Rise', cost: 40, type: 'uppercut', damage: 28 },
      { name: 'Earth Shatter', cost: 50, type: 'groundSlam', damage: 35 },
    ],
  },
  {
    id: 'shadow',
    name: 'SHADOW',
    subtitle: 'Phantom Blade',
    sprite: '/sprites/fighter3.png',
    cols: 4,
    rows: 4,
    color: 0xaa44ff,
    colorCSS: '#aa44ff',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 5, loop: true },
      walk:     { frames: [2, 3], rate: 9, loop: true },
      punch:    { frames: [4, 5], rate: 16, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 16, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 14, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 10, power: 6, defense: 4 },
    specials: [
      { name: 'Shadow Shuriken', cost: 20, type: 'fireball', damage: 18 },
      { name: 'Phantom Strike', cost: 35, type: 'uppercut', damage: 22 },
      { name: 'Void Burst', cost: 45, type: 'groundSlam', damage: 28 },
    ],
  },
  {
    id: 'titan',
    name: 'TITAN',
    subtitle: 'The Juggernaut',
    sprite: '/sprites/fighter4.png',
    cols: 4,
    rows: 4,
    color: 0xffaa00,
    colorCSS: '#ffaa00',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 3, loop: true },
      walk:     { frames: [2, 3], rate: 6, loop: true },
      punch:    { frames: [4, 5], rate: 10, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 10, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 8, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 4, power: 10, defense: 9 },
    specials: [
      { name: 'Gold Rush', cost: 25, type: 'fireball', damage: 24 },
      { name: 'Titan Uppercut', cost: 40, type: 'uppercut', damage: 32 },
      { name: 'Seismic Slam', cost: 50, type: 'groundSlam', damage: 40 },
    ],
  },
  // ── Anime Fighters ──
  {
    id: 'ryu',
    name: 'RYU',
    subtitle: 'Crimson Fist',
    sprite: '/sprites/ryu.png',
    cols: 4,
    rows: 4,
    color: 0xff4444,
    colorCSS: '#ff4444',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 4, loop: true },
      walk:     { frames: [2, 3], rate: 8, loop: true },
      punch:    { frames: [4, 5], rate: 15, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 13, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 12, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 7, power: 8, defense: 7 },
    specials: [
      { name: 'Hadou Burst', cost: 25, type: 'fireball', damage: 22 },
      { name: 'Rising Dragon', cost: 40, type: 'uppercut', damage: 28 },
      { name: 'Crimson Wave', cost: 50, type: 'groundSlam', damage: 35 },
    ],
  },
  {
    id: 'yuki',
    name: 'YUKI',
    subtitle: 'Phantom Kunoichi',
    sprite: '/sprites/kunoichi.png',
    cols: 4,
    rows: 4,
    color: 0x8844cc,
    colorCSS: '#8844cc',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 5, loop: true },
      walk:     { frames: [2, 3], rate: 10, loop: true },
      punch:    { frames: [4, 5], rate: 16, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 16, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 14, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 10, power: 6, defense: 5 },
    specials: [
      { name: 'Shadow Shuriken', cost: 20, type: 'fireball', damage: 18 },
      { name: 'Phantom Rise', cost: 35, type: 'uppercut', damage: 24 },
      { name: 'Violet Storm', cost: 45, type: 'groundSlam', damage: 30 },
    ],
  },
  // ── Realistic Fighters ──
  {
    id: 'ace',
    name: 'ACE',
    subtitle: 'The Champion',
    sprite: '/sprites/boxer.png',
    cols: 4,
    rows: 4,
    color: 0xcc2222,
    colorCSS: '#cc2222',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 3, loop: true },
      walk:     { frames: [2, 3], rate: 7, loop: true },
      punch:    { frames: [4, 5], rate: 14, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 12, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 10, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 5, power: 10, defense: 8 },
    specials: [
      { name: 'Power Jab', cost: 25, type: 'fireball', damage: 24 },
      { name: 'Champion Uppercut', cost: 40, type: 'uppercut', damage: 32 },
      { name: 'KO Haymaker', cost: 50, type: 'groundSlam', damage: 38 },
    ],
  },
  {
    id: 'valeria',
    name: 'VALERIA',
    subtitle: 'MMA Queen',
    sprite: '/sprites/valeria.png',
    cols: 4,
    rows: 4,
    color: 0xddaa22,
    colorCSS: '#ddaa22',
    frames: {
      idle: 0, idle2: 1, walk: 2, walk2: 3,
      punch_start: 4, punch: 5, kick_start: 6, kick: 7,
      block: 8, hit: 9, fireball_start: 10, fireball: 11,
      jump_rise: 12, jump_fall: 13, knockdown: 14, victory: 15,
      special: 11, grab: 5,
    },
    animations: {
      idle:     { frames: [0, 1], rate: 4, loop: true },
      walk:     { frames: [2, 3], rate: 9, loop: true },
      punch:    { frames: [4, 5], rate: 14, loop: false, hitFrame: 1 },
      kick:     { frames: [6, 7], rate: 14, loop: false, hitFrame: 1 },
      block:    { frames: [8], rate: 1, loop: false },
      hurt:     { frames: [9], rate: 1, loop: false },
      fireball: { frames: [10, 11], rate: 12, loop: false },
      jump:     { frames: [12, 13], rate: 10, loop: false },
      knockdown:{ frames: [14], rate: 1, loop: false },
      victory:  { frames: [15], rate: 1, loop: false },
    },
    stats: { speed: 9, power: 7, defense: 6 },
    specials: [
      { name: 'Gold Strike', cost: 25, type: 'fireball', damage: 20 },
      { name: 'Knee Rocket', cost: 40, type: 'uppercut', damage: 26 },
      { name: 'Burnout Wave', cost: 50, type: 'groundSlam', damage: 32 },
    ],
  },
  // ── 3D Fighter ──
  {
    id: 'iron',
    name: 'IRON',
    subtitle: '3D Fighter',
    is3D: true,
    model: '/models/fighter3d.glb',
    sprite: null,
    cols: 1,
    rows: 1,
    color: 0x4488ff,
    colorCSS: '#4488ff',
    frames: {
      idle: 0, idle2: 0, walk: 0, walk2: 0,
      punch_start: 0, punch: 0, kick_start: 0, kick: 0,
      block: 0, hit: 0, fireball_start: 0, fireball: 0,
      jump_rise: 0, jump_fall: 0, knockdown: 0, victory: 0,
      special: 0, grab: 0,
    },
    animations: {
      idle:     { frames: [0], rate: 1, loop: true },
      walk:     { frames: [0], rate: 1, loop: true },
      punch:    { frames: [0], rate: 1, loop: false, hitFrame: 0 },
      kick:     { frames: [0], rate: 1, loop: false, hitFrame: 0 },
      block:    { frames: [0], rate: 1, loop: false },
      hurt:     { frames: [0], rate: 1, loop: false },
      fireball: { frames: [0], rate: 1, loop: false },
      jump:     { frames: [0], rate: 1, loop: false },
      knockdown:{ frames: [0], rate: 1, loop: false },
      victory:  { frames: [0], rate: 1, loop: false },
    },
    stats: { speed: 7, power: 9, defense: 7 },
    specials: [
      { name: 'Iron Fist', cost: 25, type: 'fireball', damage: 24 },
      { name: 'Steel Uppercut', cost: 40, type: 'uppercut', damage: 30 },
      { name: 'Shockwave', cost: 50, type: 'groundSlam', damage: 36 },
    ],
  },
];
