/* ═══ /c/:shareId — credential share card ═══
 *
 * AP-ENGAGEMENT-LOOP-2026-05 · Lane 3
 *
 * Single big share card view for a credential (badge or certificate). This
 * is the URL members paste into LinkedIn, X, Bluesky, etc. — designed to
 * render as a rich preview card via OG metadata.
 *
 * RLS gates this on the owning profile's visibility. If the owner flips back
 * to 'private', the share URL 404s for everyone but the owner.
 *
 * OG image is generated by the og-image Edge Function (Lane 2 ships it) —
 * we pass `?credentialId=<shareId>` so it renders the right card.
 */

import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import {
  ArrowRight,
  CheckCircle,
  Spinner,
  Trophy,
  Sparkle,
} from '@phosphor-icons/react';
import SEOHead from '../components/seo/SEOHead';
import NotFound from './NotFound';
import {
  getCredentialByShareId,
  type CredentialSharePayload,
} from '../data/publicProfile';
import { useAuth } from '../context/useAuth';
import './CredentialShare.css';

const BASE_URL = 'https://www.assetpersona.com';

export default function CredentialShare() {
  const { shareId } = useParams<{ shareId: string }>();
  const { user } = useAuth();
  const [state, setState] = useState<
    | { kind: 'loading' }
    | { kind: 'not-found' }
    | { kind: 'loaded'; data: CredentialSharePayload }
  >({ kind: 'loading' });

  useEffect(() => {
    let cancelled = false;
    if (!shareId) {
      setState({ kind: 'not-found' });
      return;
    }
    setState({ kind: 'loading' });
    void (async () => {
      const payload = await getCredentialByShareId(shareId);
      if (cancelled) return;
      if (!payload) {
        setState({ kind: 'not-found' });
        return;
      }
      // Private profiles route through 404 even when the credential row itself
      // resolves (e.g. owner viewing their own).
      if (payload.profile.visibility === 'private') {
        setState({ kind: 'not-found' });
        return;
      }
      setState({ kind: 'loaded', data: payload });
    })();
    return () => {
      cancelled = true;
    };
  }, [shareId]);

  if (state.kind === 'loading') {
    return (
      <div className="credshare credshare--loading">
        <Spinner size={28} className="credshare__spinner" />
        <p>Loading credential…</p>
      </div>
    );
  }

  if (state.kind === 'not-found') {
    return <NotFound />;
  }

  const { credential, profile, moduleTitle, moduleSlug } = state.data;
  const earnedOn = new Date(credential.earned_at);
  const earnedLabel = earnedOn.toLocaleDateString(undefined, {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  // OG image: hand off to the og-image Edge Function (Lane 2). We pass the
  // shareId so the function looks up the credential server-side and renders.
  const ogImageUrl = `${BASE_URL}/functions/v1/og-image?credentialId=${encodeURIComponent(credential.share_id)}`;
  const ogTitle = `${profile.display_name} earned: ${credential.label}`;
  const ogDescription = moduleTitle
    ? `${credential.kind === 'certificate' ? 'Certificate' : 'Badge'} for completing ${moduleTitle} on Asset Persona.`
    : `${credential.kind === 'certificate' ? 'Certificate' : 'Badge'} earned on Asset Persona.`;

  return (
    <>
      <SEOHead
        title={ogTitle}
        description={ogDescription}
        path={`/c/${credential.share_id}`}
        image={ogImageUrl}
        type="article"
      />

      <article className="credshare">
        <div className="credshare__card">
          {/* Brand wordmark — recognizable from the share preview */}
          <header className="credshare__brand">
            <Sparkle size={20} weight="fill" />
            <span>Asset Persona</span>
          </header>

          {/* Earner block */}
          <div className="credshare__earner">
            {profile.avatar_url ? (
              <img
                src={profile.avatar_url}
                alt={profile.display_name}
                className="credshare__avatar"
              />
            ) : (
              <div className="credshare__avatar credshare__avatar--initial" aria-hidden="true">
                {profile.display_name.charAt(0).toUpperCase()}
              </div>
            )}
            <div className="credshare__earner-text">
              <p className="credshare__earner-label">Awarded to</p>
              <h2 className="credshare__earner-name">{profile.display_name}</h2>
              {profile.handle && (
                <Link to={`/u/${profile.handle}`} className="credshare__earner-handle">
                  @{profile.handle}
                </Link>
              )}
            </div>
          </div>

          {/* Credential block — the star of the card */}
          <div className="credshare__credential">
            <span className="credshare__kind">
              <Trophy size={14} weight="fill" />
              {credential.kind === 'certificate' ? 'Certificate' : 'Badge'}
            </span>
            <h1 className="credshare__label">{credential.label}</h1>
            {moduleTitle && (
              <p className="credshare__module">
                For completing{' '}
                {moduleSlug ? (
                  <Link to={`/learn/${moduleSlug}`}>{moduleTitle}</Link>
                ) : (
                  <strong>{moduleTitle}</strong>
                )}
              </p>
            )}
            <p className="credshare__earned">
              <CheckCircle size={14} weight="fill" /> Earned {earnedLabel}
            </p>
          </div>

          {/* Footer CTA — for non-members it's a signup hook, for members it's a soft handoff */}
          <footer className="credshare__footer">
            {user ? (
              <Link to="/community/learn" className="btn btn--ghost btn--sm">
                See more modules <ArrowRight size={14} />
              </Link>
            ) : (
              <>
                <p className="credshare__footer-copy">
                  Want one of these on your own profile?
                </p>
                <Link
                  to={`/login?intent=signup&ref=${encodeURIComponent(`/c/${credential.share_id}`)}`}
                  className="btn btn--primary btn--sm"
                >
                  Get started free <ArrowRight size={14} />
                </Link>
              </>
            )}
          </footer>
        </div>

        <p className="credshare__permalink">
          {BASE_URL}/c/{credential.share_id}
        </p>
      </article>
    </>
  );
}
